export enum ACCOUNT_TYPE {
    STUDENT = "STUDENT", 
    EMPLOYEE = "EMPLOYEE"
}

export enum ACCOUNT_STATUS{
    APPROVAL_PENDING = "APPROVAL_PENDING",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE", 
    BLOCKED = "BLOCKED", 
    DELETED = "DELETED",
}